export const uiCopy = {
  common: {
    refresh: 'Refresh',
    retry: 'Retry',
    cancel: 'Cancel',
    loading: 'Loading...',
    selectCourse: 'Select course',
  },
  app: {
    brandTitle: 'FPT University',
    brandSubtitle: 'AI Tutor',
  },
  student: {
    chat: {
      title: 'Trò chuyện với AI Tutor',
      subtitle: 'Hỏi theo môn học và xem lại lịch sử trao đổi của bạn.',
      empty: 'Hãy đặt câu hỏi đầu tiên',
      inputPlaceholder: 'Nhập câu hỏi...',
      searchPlaceholder: 'Tìm cuộc trò chuyện...',
      sessionLabel: 'Phiên học theo môn',
      questionCounter: (count) => `Câu hỏi ${count}/10`,
      almostFull: 'Cuộc trò chuyện sắp đầy. AI Tutor sẽ tạo cuộc trò chuyện mới sau 10 câu hỏi.',
      full: 'Cuộc trò chuyện đã đủ 10 câu hỏi. Hãy tạo cuộc trò chuyện mới để tiếp tục.',
      switchTitle: 'Đổi môn học?',
      switchDescription: 'Mỗi môn có lịch sử trò chuyện riêng. Khi đổi môn, hệ thống sẽ mở lịch sử của môn đó.',
      newConversationTitle: 'Đã tạo cuộc trò chuyện mới',
      rolloverMessage: 'Cuộc trò chuyện đã đủ 10 câu hỏi. AI Tutor đã tự động tạo cuộc trò chuyện mới.',
      previousConversation: 'Quay lại cuộc trò chuyện trước',
    },
    codeReview: {
      title: 'Code Review',
      subtitle: 'Paste source code or an error log to get focused debugging guidance.',
      empty: 'No analysis yet.',
      inputPlaceholder: 'Paste source code or an exception log...',
      action: 'Analyze code',
    },
    avatar: {
      title: 'Tutor Avatar',
      subtitle: 'This avatar visualizes the AI tutor state. It is not a separate chatbot.',
    },
    progress: {
      title: 'Learning Progress',
      subtitle: 'Review what you have learned, weak topics, and AI study suggestions.',
      learnedTitle: 'Learned',
      weakTitle: 'Needs improvement',
      suggestionsTitle: 'AI Study Suggestions',
    },
    quizzes: {
      title: 'Practice with material-grounded quizzes',
      subtitle: 'Generate focused self-study quizzes, complete teacher assignments, and review mistakes without exposing answers before submit.',
      noActive: 'No active quiz. Generate or continue a quiz to start.',
      noResult: 'No quiz result selected yet.',
      contextRequired: 'Practice quizzes require a student and course context.',
      activeReady: 'You have an active quiz ready',
      preparing: 'Preparing quiz from indexed course materials...',
    },
    materials: {
      title: 'Materials & Assignments',
      subtitle: 'Open assignment details, download attachments, and submit your work.',
      empty: 'Select an assignment to view details',
      uploadText: 'Drag a file here or click to choose',
      uploadHint: 'Supports ZIP, PDF, DOCX (max 50MB)',
    },
    support: {
      title: 'Teacher Support',
      subtitle: 'Choose a matched teacher, discuss the question, and track the official final answer.',
      listTitle: 'Support Requests',
      emptyTitle: 'No support requests yet',
      emptyDescription: 'Ask AI Tutor a difficult question first. Low-confidence answers can open teacher support here.',
      detailEmpty: 'Select a support request to view details',
    },
  },
  teacher: {
    supportKnowledgeTitle: 'Support Queue & AI Knowledge',
    knowledgeUploadTitle: 'AI Knowledge Upload Status',
    suggestedAnswerTitle: 'Review Suggested AI Answers',
  },
};
