export const uiCopy = {
  common: {
    refresh: 'Refresh',
    retry: 'Retry',
    cancel: 'Cancel',
    loading: 'Loading...',
    selectCourse: 'Select course',
  },
  app: {
    brandTitle: 'FPT University',
    brandSubtitle: 'AI Tutor',
  },
  student: {
    chat: {
      title: 'AI Tutor Chat',
      subtitle: 'Ask course questions and keep each learning topic in a separate conversation.',
      empty: 'Ask your first question',
      inputPlaceholder: 'Enter your question...',
      searchPlaceholder: 'Search conversations...',
      sessionLabel: 'Course AI session',
      questionCounter: (count) => `Questions ${count}/10`,
      almostFull: 'This chat is almost full. AI Tutor will continue in a new chat after 10 questions.',
      full: 'This chat is full. Start a new chat to continue.',
      switchTitle: 'Switch course?',
      switchDescription: 'Each course has separate chat history. Switching course opens that course\'s conversations.',
      newConversationTitle: 'New conversation started',
      rolloverMessage: 'This chat reached 10 questions. AI Tutor started a new conversation.',
      previousConversation: 'Back to previous chat',
    },
    codeReview: {
      title: 'Code Review',
      subtitle: 'Paste source code or an error log to get focused debugging guidance.',
      empty: 'No analysis yet.',
      inputPlaceholder: 'Paste source code or an exception log...',
      action: 'Analyze code',
    },
    avatar: {
      title: 'Tutor Avatar',
      subtitle: 'This avatar visualizes the AI tutor state. It is not a separate chatbot.',
    },
    progress: {
      title: 'Learning Progress',
      subtitle: 'Review what you have learned, weak topics, and AI study suggestions.',
      networkTitle: 'Course Knowledge Network',
      learnedTitle: 'Learned',
      weakTitle: 'Needs improvement',
      suggestionsTitle: 'AI Study Suggestions',
    },
    quizzes: {
      title: 'Practice with material-grounded quizzes',
      subtitle: 'Generate focused self-study quizzes, complete teacher assignments, and review mistakes without exposing answers before submit.',
      noActive: 'No active quiz. Generate or continue a quiz to start.',
      noResult: 'No quiz result selected yet.',
      contextRequired: 'Practice quizzes require a student and course context.',
      activeReady: 'You have an active quiz ready',
      preparing: 'Preparing quiz from indexed course materials...',
    },
    materials: {
      title: 'Materials & Assignments',
      subtitle: 'Open assignment details, download attachments, and submit your work.',
      empty: 'Select an assignment to view details',
      uploadText: 'Drag a file here or click to choose',
      uploadHint: 'Supports ZIP, PDF, DOCX (max 50MB)',
    },
    support: {
      title: 'Teacher Support',
      subtitle: 'Choose a matched teacher, discuss the question, and track the official final answer.',
      listTitle: 'Support Requests',
      emptyTitle: 'No support requests yet',
      emptyDescription: 'Ask AI Tutor a difficult question first. Low-confidence answers can open teacher support here.',
      detailEmpty: 'Select a support request to view details',
    },
  },
  teacher: {
    supportKnowledgeTitle: 'Support Queue & AI Knowledge',
    knowledgeUploadTitle: 'AI Knowledge Upload Status',
    suggestedAnswerTitle: 'Review Suggested AI Answers',
  },
};
