export const queryKeys = {
  conversations: (userId, courseId) => [
    'conversations',
    userId,
    courseId || 'all',
  ],
  conversationMessages: (conversationId, userId) => [
    'conversation',
    conversationId || 'none',
    'messages',
    userId || 'anonymous',
  ],
  pinnedConversationMessages: (conversationId, userId) => [
    'conversation',
    conversationId || 'none',
    'pinned-messages',
    userId || 'anonymous',
  ],
  ttsVoices: (courseId, classId) => [
    'tts',
    'voices',
    courseId || 'none',
    classId || 'none',
  ],
  profile: (userId) => ['account', 'profile', userId],
  studentEnrollments: (identityKey) => ['student', 'enrollments', identityKey],
  studentQuestionQuota: (studentId, courseId) => [
    'student',
    'question-quota',
    studentId,
    courseId,
  ],
  studentAssignments: (studentId, courseId, filters = {}) => [
    'student',
    'assignments',
    studentId || 'anonymous',
    courseId || 'all',
    Number(filters.page) || 0,
    Number(filters.pageSize) || 8,
    String(filters.query || '').trim(),
  ],
  studentQuizHistory: (studentId, courseId) => [
    'quizzes',
    studentId || 'anonymous',
    courseId || 'all',
    'history',
  ],
  studentAssignedQuizzes: (studentId, courseId, classId) => [
    'quizzes',
    studentId || 'anonymous',
    courseId || 'all',
    'assigned',
    classId || 'all',
  ],
  studentLearning: (studentId, courseId) => [
    'student',
    'learning',
    studentId || 'anonymous',
    courseId || 'none',
  ],
  quizDetail: (quizId) => ['quiz', 'detail', quizId || 'none'],
  courseMaterials: ({ courseId, classId, studentId, teacherId, filters = {} }) => [
    'materials',
    courseId || 'none',
    studentId ? 'student' : 'staff',
    studentId || teacherId || 'anonymous',
    classId || 'all',
    Number(filters.page) || 0,
    Number(filters.pageSize) || 8,
    String(filters.query || '').trim(),
  ],
  teacherAssignments: (teacherId, courseId, classId) => [
    'teacher',
    'assignments',
    teacherId || 'anonymous',
    courseId || 'none',
    classId || 'none',
  ],
  assignmentDetail: (assignmentId) => [
    'assignment',
    'detail',
    assignmentId || 'none',
  ],
  teacherClasses: (teacherId) => [
    'teacher',
    'classes',
    teacherId || 'anonymous',
  ],
  teacherClassRoster: (teacherId, courseId, classId) => [
    'teacher',
    'class-roster',
    teacherId || 'anonymous',
    courseId || 'none',
    classId || 'none',
  ],
  teacherDashboard: (teacherId, courseId, classId) => [
    'teacher',
    'dashboard',
    teacherId || 'anonymous',
    courseId || 'all',
    classId || 'all',
  ],
  adminUsers: (filters = {}) => [
    'admin',
    'users',
    String(filters.search || '').trim(),
    filters.role || 'all',
  ],
  adminMentors: () => ['admin', 'mentors'],
  adminEscalations: () => ['admin', 'mentor-escalations'],
  adminDashboardStats: () => ['admin', 'dashboard', 'stats'],
  adminHarnessLogs: (filters = {}) => ['admin', 'harness-logs', filters],
  adminHarnessTrace: (traceId) => ['admin', 'harness-trace', traceId || 'none'],
  adminAiLogs: (filters = {}) => ['admin', 'ai-logs', filters],
  adminLlmProviders: () => ['admin', 'llm-providers', 'configuration'],
  adminLlmProviderStats: () => ['admin', 'llm-providers', 'stats'],
  adminSemesters: () => ['admin', 'academic', 'semesters'],
  adminCourses: () => ['admin', 'academic', 'courses'],
  adminClassSections: (courseId) => ['admin', 'academic', 'class-sections', courseId || 'none'],
  adminStudentEnrollments: (search) => [
    'admin',
    'academic',
    'student-enrollments',
    String(search || '').trim(),
  ],
  adminStudentSearch: (search) => ['admin', 'student-search', String(search || '').trim()],
  adminMentorOptions: () => ['admin', 'academic', 'mentor-options'],
  adminCourseMaterials: (courseId) => ['admin', 'academic', 'materials', courseId || 'none'],
  adminIndexedTeachingNotes: (courseId, status) => [
    'admin',
    'indexed-teaching-notes',
    courseId || 'all',
    status || 'all',
  ],
  teacherActionCenter: (teacherId, role, courseId, classId) => [
    'teacher',
    'action-center',
    teacherId || 'anonymous',
    role || 'teacher',
    courseId || 'none',
    classId || 'none',
  ],
  teacherGradingAssignments: (teacherId, courseId, classId) => [
    'teacher',
    'grading',
    'assignments',
    teacherId || 'anonymous',
    courseId || 'none',
    classId || 'none',
  ],
  teacherGradingQuizzes: (teacherId, courseId, classId, reviewStatus, page) => [
    'teacher',
    'grading',
    'quizzes',
    teacherId || 'anonymous',
    courseId || 'none',
    classId || 'none',
    reviewStatus || 'all',
    Number(page) || 0,
  ],
  teacherQuizAssignments: (teacherId) => [
    'teacher',
    'quiz-assignments',
    teacherId || 'anonymous',
  ],
  teacherQuizScoreboard: (teacherId, assignmentId, courseId, classId) => [
    'teacher',
    'quiz-scoreboard',
    teacherId || 'anonymous',
    assignmentId || 'none',
    courseId || 'none',
    classId || 'none',
  ],
  teacherAssignmentSubmissions: (teacherId, courseId, classId) => [
    'teacher',
    'grading',
    'assignment-submissions',
    teacherId || 'anonymous',
    courseId || 'none',
    classId || 'none',
  ],
  teacherQuizSubmissions: (teacherId, courseId, classId, filters = {}) => [
    'teacher',
    'grading',
    'quiz-submissions',
    teacherId || 'anonymous',
    courseId || 'none',
    classId || 'none',
    filters.reviewStatus || 'all',
    Number(filters.page) || 0,
    Number(filters.pageSize) || 20,
  ],
  studentMentorRequests: (studentId) => ['student', 'mentor-requests', studentId],
  studentMentorRequestDetail: (escalationId) => [
    'student',
    'mentor-request-detail',
    escalationId,
  ],
  supportChatRoom: (chatRoomId) => ['support', 'chat-room', chatRoomId],
  answerCache: (courseId, filters = {}) => [
    'admin',
    'answer-cache',
    courseId,
    filters.classId || '',
    filters.mode || '',
    filters.reviewStatus || '',
  ],
};
