export const queryKeys = {
  conversations: (userId, courseId) => [
    'conversations',
    userId,
    courseId || 'all',
  ],
  conversationMessages: (conversationId, userId) => [
    'conversation',
    conversationId || 'none',
    'messages',
    userId || 'anonymous',
  ],
  pinnedConversationMessages: (conversationId, userId) => [
    'conversation',
    conversationId || 'none',
    'pinned-messages',
    userId || 'anonymous',
  ],
  ttsVoices: (courseId, classId) => [
    'tts',
    'voices',
    courseId || 'none',
    classId || 'none',
  ],
  profile: (userId) => ['account', 'profile', userId],
  studentEnrollments: (identityKey) => ['student', 'enrollments', identityKey],
  studentQuestionQuota: (studentId, courseId) => [
    'student',
    'question-quota',
    studentId,
    courseId,
  ],
  studentAssignments: (studentId, courseId, filters = {}) => [
    'student',
    'assignments',
    studentId || 'anonymous',
    courseId || 'all',
    Number(filters.page) || 0,
    Number(filters.pageSize) || 8,
    String(filters.query || '').trim(),
  ],
  studentQuizHistory: (studentId, courseId) => [
    'quizzes',
    studentId || 'anonymous',
    courseId || 'all',
    'history',
  ],
  studentAssignedQuizzes: (studentId, courseId, classId) => [
    'quizzes',
    studentId || 'anonymous',
    courseId || 'all',
    'assigned',
    classId || 'all',
  ],
  studentLearning: (studentId, courseId) => [
    'student',
    'learning',
    studentId || 'anonymous',
    courseId || 'none',
  ],
  quizDetail: (quizId) => ['quiz', 'detail', quizId || 'none'],
  courseMaterials: ({ courseId, classId, studentId, teacherId, filters = {} }) => [
    'materials',
    courseId || 'none',
    studentId ? 'student' : 'staff',
    studentId || teacherId || 'anonymous',
    classId || 'all',
    Number(filters.page) || 0,
    Number(filters.pageSize) || 8,
    String(filters.query || '').trim(),
  ],
  teacherAssignments: (teacherId, courseId, classId) => [
    'teacher',
    'assignments',
    teacherId || 'anonymous',
    courseId || 'none',
    classId || 'none',
  ],
  assignmentDetail: (assignmentId) => [
    'assignment',
    'detail',
    assignmentId || 'none',
  ],
  teacherClasses: (teacherId) => [
    'teacher',
    'classes',
    teacherId || 'anonymous',
  ],
  teacherClassRoster: (teacherId, courseId, classId) => [
    'teacher',
    'class-roster',
    teacherId || 'anonymous',
    courseId || 'none',
    classId || 'none',
  ],
  teacherDashboard: (teacherId, courseId, classId) => [
    'teacher',
    'dashboard',
    teacherId || 'anonymous',
    courseId || 'all',
    classId || 'all',
  ],
  studentMentorRequests: (studentId) => ['student', 'mentor-requests', studentId],
  studentMentorRequestDetail: (escalationId) => [
    'student',
    'mentor-request-detail',
    escalationId,
  ],
  supportChatRoom: (chatRoomId) => ['support', 'chat-room', chatRoomId],
  answerCache: (courseId, filters = {}) => [
    'admin',
    'answer-cache',
    courseId,
    filters.classId || '',
    filters.mode || '',
    filters.reviewStatus || '',
  ],
};
