import {
  MessageSquare,
  TrendingUp,
  BookOpen,
  ClipboardList,
  LayoutGrid,
  UploadCloud,
  CheckSquare,
  Inbox,
  BarChart3,
  Users,
  Library,
  MessageCircle,
  BrainCircuit,
} from 'lucide-react';
import { getWorkspaceRole } from '../constants/roles';

const navigationItems = [
  {
    key: 'student-chat',
    workspace: 'student',
    group: 'Học tập',
    label: 'Trò chuyện AI Tutor',
    description: 'Hỏi theo môn học và xem lại lịch sử trò chuyện.',
    icon: MessageSquare,
  },
  {
    key: 'student-memory',
    workspace: 'student',
    group: 'Học tập',
    label: 'Tiến độ học tập',
    description: 'Xem chủ đề đã học, điểm yếu và gợi ý ôn tập.',
    icon: TrendingUp,
  },
  {
    key: 'student-quizzes',
    workspace: 'student',
    group: 'Học tập',
    label: 'Quiz luyện tập',
    description: 'Tạo quiz tự ôn và làm quiz được giảng viên giao.',
    icon: ClipboardList,
  },
  {
    key: 'student-materials',
    workspace: 'student',
    group: 'Học liệu',
    label: 'Tài liệu & bài tập',
    description: 'Xem tài liệu, tải đề và nộp bài tập.',
    icon: BookOpen,
  },
  {
    key: 'student-escalation',
    workspace: 'student',
    group: 'Hỗ trợ',
    label: 'Hỗ trợ từ giảng viên',
    description: 'Trao đổi câu hỏi khó và theo dõi câu trả lời chính thức.',
    icon: MessageCircle,
  },
  {
    key: 'teacher-classes',
    workspace: 'teacher',
    group: 'Giảng dạy',
    label: 'Lớp được phân công',
    description: 'Xem lớp, sinh viên và các chủ đề còn yếu.',
    icon: LayoutGrid,
  },
  {
    key: 'teacher-quizzes',
    workspace: 'teacher',
    group: 'Giảng dạy',
    label: 'Quiz được giao',
    description: 'Tạo, xuất bản quiz và duyệt bài làm của sinh viên.',
    icon: ClipboardList,
  },
  {
    key: 'teacher-materials',
    workspace: 'teacher',
    group: 'Giảng dạy',
    label: 'Tài liệu & bài tập',
    description: 'Xem học liệu và giao bài tập cho lớp.',
    icon: UploadCloud,
  },
  {
    key: 'teacher-grading',
    workspace: 'teacher',
    group: 'Giảng dạy',
    label: 'Chấm bài nộp',
    description: 'Chấm bài sinh viên và công bố nhận xét.',
    icon: CheckSquare,
  },
  {
    key: 'teacher-escalations',
    workspace: 'teacher',
    group: 'Hỗ trợ',
    label: 'Hàng chờ hỗ trợ & tri thức AI',
    description: 'Xử lý câu hỏi được chuyển lên và kiểm tra phản hồi AI.',
    icon: Inbox,
  },
  {
    key: 'teacher-expert-training',
    workspace: 'teacher',
    group: 'Chất lượng AI',
    label: 'Huấn luyện tri thức AI',
    description: 'Nhận task, đóng góp tri thức tin cậy và xem Evaluation Tutor V2.',
    icon: BrainCircuit,
  },
  {
    key: 'admin-dashboard',
    workspace: 'admin',
    group: 'Hệ thống',
    label: 'Tổng quan hệ thống',
    description: 'Theo dõi trạng thái nền tảng và chẩn đoán kỹ thuật.',
    icon: BarChart3,
  },
  {
    key: 'admin-users',
    workspace: 'admin',
    group: 'Hệ thống',
    label: 'Tài khoản & giảng viên',
    description: 'Quản lý tài khoản, giảng viên và dữ liệu import.',
    icon: Users,
  },
  {
    key: 'admin-academic',
    workspace: 'admin',
    group: 'Học vụ',
    label: 'Học kỳ & lớp học',
    description: 'Quản lý học kỳ, môn học và lớp học phần.',
    icon: Library,
  },
  {
    key: 'admin-expert-training',
    workspace: 'admin',
    group: 'Chất lượng AI',
    label: 'Huấn luyện tri thức AI',
    description: 'Phân tích độ phủ, duyệt tri thức và đánh giá chất lượng Tutor V2.',
    icon: BrainCircuit,
  },
  {
    key: 'admin-review',
    workspace: 'admin',
    group: 'Chất lượng AI',
    label: 'Kiểm duyệt phản hồi AI',
    description: 'Xử lý phản hồi nghiêm trọng và Knowledge Candidate đang chờ duyệt.',
    icon: Inbox,
  },
];

export const getNavigationForRole = (role) => {
  const workspace = getWorkspaceRole(role);
  return navigationItems.filter((item) => item.workspace === workspace);
};
