import {
  MessageSquare,
  TrendingUp,
  BookOpen,
  ClipboardList,
  LayoutGrid,
  UploadCloud,
  CheckSquare,
  Inbox,
  BarChart3,
  Users,
  Library,
  MessageCircle,
} from 'lucide-react';

export const navigationItems = [
  {
    key: 'student-chat',
    role: 'student',
    group: 'Learning',
    label: 'AI Tutor Chat',
    description: 'Ask course questions and review past conversations.',
    icon: MessageSquare,
  },
  {
    key: 'student-memory',
    role: 'student',
    group: 'Learning',
    label: 'Learning Progress',
    description: 'See learned topics, weak areas, and study suggestions.',
    icon: TrendingUp,
  },
  {
    key: 'student-quizzes',
    role: 'student',
    group: 'Learning',
    label: 'Practice Quizzes',
    description: 'Create self-study quizzes and complete assigned quizzes.',
    icon: ClipboardList,
  },
  {
    key: 'student-materials',
    role: 'student',
    group: 'Coursework',
    label: 'Materials & Assignments',
    description: 'Download assignments and submit your work.',
    icon: BookOpen,
  },
  {
    key: 'student-escalation',
    role: 'student',
    group: 'Support',
    label: '1-on-1 Support',
    description: 'Continue mentor help for difficult questions.',
    icon: MessageCircle,
  },
  {
    key: 'teacher-classes',
    role: 'teacher',
    group: 'Teaching',
    label: 'Assigned Classes',
    description: 'Review classes, students, and weak topics.',
    icon: LayoutGrid,
  },
  {
    key: 'teacher-quizzes',
    role: 'teacher',
    group: 'Teaching',
    label: 'Quiz Assignments',
    description: 'Manage quiz assignments and review attempts.',
    icon: ClipboardList,
  },
  {
    key: 'teacher-materials',
    role: 'teacher',
    group: 'Teaching',
    label: 'Materials & Assignments',
    description: 'View course materials and publish class assignments.',
    icon: UploadCloud,
  },
  {
    key: 'teacher-grading',
    role: 'teacher',
    group: 'Teaching',
    label: 'Submission Grading',
    description: 'Review student submissions and publish feedback.',
    icon: CheckSquare,
  },
  {
    key: 'teacher-escalations',
    role: 'teacher',
    group: 'Support',
    label: 'Support Queue & AI Knowledge',
    description: 'Answer escalated questions and review suggested AI answers.',
    icon: Inbox,
  },
  {
    key: 'teacher-chat',
    role: 'teacher',
    group: 'Support',
    label: '1-on-1 Support',
    description: 'Manage direct support conversations.',
    icon: MessageCircle,
  },
  {
    key: 'admin-dashboard',
    role: 'admin',
    group: 'System',
    label: 'Overview Dashboard',
    description: 'Monitor platform health and diagnostics.',
    icon: BarChart3,
  },
  {
    key: 'admin-users',
    role: 'admin',
    group: 'System',
    label: 'Users & Mentors',
    description: 'Manage accounts, mentors, and imports.',
    icon: Users,
  },
  {
    key: 'admin-academic',
    role: 'admin',
    group: 'Academic',
    label: 'Terms & Classes',
    description: 'Manage semesters, courses, and class sections.',
    icon: Library,
  },
];

export const getNavigationForRole = (role) => {
  const normalizedRole = String(role || '').trim().toLowerCase();
  return navigationItems.filter((item) => item.role === normalizedRole);
};

export const getNavigationItem = (key) => navigationItems.find((item) => item.key === key);
