import {
  MessageSquare,
  TrendingUp,
  BookOpen,
  ClipboardList,
  LayoutGrid,
  UploadCloud,
  CheckSquare,
  Inbox,
  BarChart3,
  Users,
  Library,
  MessageCircle,
  BrainCircuit,
  FileText,
  House,
  RefreshCw,
  Database,
} from 'lucide-react';
import { ACCOUNT_ROLES, getWorkspaceRole, normalizeAccountRole } from '../constants/roles';

const navigationItems = [
  {
    key: 'student-dashboard',
    workspace: 'student',
    group: 'Học tập',
    label: 'Tổng quan',
    description: 'Xem nhanh các môn đang học, lớp tham gia và lối tắt học tập.',
    icon: House,
  },
  {
    key: 'student-chat',
    workspace: 'student',
    group: 'Học tập',
    label: 'Trò chuyện AI Tutor',
    description: 'Hỏi theo môn học và xem lại lịch sử trò chuyện.',
    icon: MessageSquare,
  },
  {
    key: 'student-memory',
    workspace: 'student',
    group: 'Học tập',
    label: 'Tiến độ học tập',
    description: 'Xem chủ đề đã học, điểm yếu và gợi ý ôn tập.',
    icon: TrendingUp,
  },
  {
    key: 'student-quizzes',
    workspace: 'student',
    group: 'Học tập',
    label: 'Quiz luyện tập',
    description: 'Tạo quiz tự ôn và làm quiz được giảng viên giao.',
    icon: ClipboardList,
  },
  {
    key: 'student-materials',
    workspace: 'student',
    group: 'Học liệu',
    label: 'Tài liệu & bài tập',
    description: 'Xem tài liệu, tải đề và nộp bài tập.',
    icon: BookOpen,
  },
  {
    key: 'student-escalation',
    workspace: 'student',
    group: 'Hỗ trợ',
    label: 'Hỗ trợ từ giảng viên',
    description: 'Trao đổi câu hỏi khó và theo dõi câu trả lời chính thức.',
    icon: MessageCircle,
  },
  {
    key: 'teacher-classes',
    workspace: 'teacher',
    allowedAccountRoles: [ACCOUNT_ROLES.TEACHER],
    group: 'Giảng dạy',
    label: 'Lớp được phân công',
    description: 'Xem lớp, sinh viên và các chủ đề còn yếu.',
    icon: LayoutGrid,
  },
  {
    key: 'teacher-quizzes',
    workspace: 'teacher',
    allowedAccountRoles: [ACCOUNT_ROLES.TEACHER],
    group: 'Giảng dạy',
    label: 'Quiz được giao',
    description: 'Tạo, xuất bản quiz và duyệt bài làm của sinh viên.',
    icon: ClipboardList,
  },
  {
    key: 'teacher-materials',
    workspace: 'teacher',
    allowedAccountRoles: [ACCOUNT_ROLES.TEACHER],
    group: 'Giảng dạy',
    label: 'Tài liệu & bài tập',
    description: 'Xem học liệu và giao bài tập cho lớp.',
    icon: UploadCloud,
  },
  {
    key: 'teacher-grading',
    workspace: 'teacher',
    allowedAccountRoles: [ACCOUNT_ROLES.TEACHER],
    group: 'Giảng dạy',
    label: 'Chấm bài nộp',
    description: 'Chấm bài sinh viên và công bố nhận xét.',
    icon: CheckSquare,
  },
  {
    key: 'teacher-escalations',
    workspace: 'teacher',
    allowedAccountRoles: [ACCOUNT_ROLES.TEACHER],
    group: 'Hỗ trợ',
    label: 'Hàng chờ hỗ trợ & tri thức AI',
    description: 'Xử lý câu hỏi được chuyển lên và kiểm tra phản hồi AI.',
    icon: Inbox,
  },
  {
    key: 'teacher-expert-training',
    workspace: 'teacher',
    allowedAccountRoles: [ACCOUNT_ROLES.TEACHER],
    group: 'Chất lượng AI',
    label: 'Q&A huấn luyện AI',
    description: 'Nhận việc viết Q&A vàng theo chương giáo trình.',
    icon: BrainCircuit,
  },
  {
    key: 'senior-v2',
    workspace: 'senior',
    allowedAccountRoles: [ACCOUNT_ROLES.SENIOR_MENTOR],
    group: 'Kiểm duyệt chuyên môn',
    label: 'Huấn luyện AI',
    description: 'Mục lục sách, giao Q&A vàng, xem bài thi rồi nạp RAG.',
    icon: BrainCircuit,
  },
  {
    key: 'senior-review',
    workspace: 'senior',
    allowedAccountRoles: [ACCOUNT_ROLES.SENIOR_MENTOR],
    group: 'Kiểm duyệt chuyên môn',
    label: 'Trung tâm kiểm duyệt',
    description: 'Xử lý phản hồi nghiêm trọng và Knowledge Candidate, không can thiệp chat lớp.',
    icon: Inbox,
  },
  {
    key: 'senior-answer-cache',
    workspace: 'senior',
    allowedAccountRoles: [ACCOUNT_ROLES.SENIOR_MENTOR],
    group: 'Kiểm duyệt chuyên môn',
    label: 'Cache câu trả lời AI',
    description: 'Duyệt, sửa hoặc tắt câu trả lời AI đã cache theo semantic similarity.',
    icon: Database,
  },
  {
    key: 'admin-dashboard',
    workspace: 'admin',
    group: 'Hệ thống',
    label: 'Tổng quan hệ thống',
    description: 'Theo dõi trạng thái nền tảng và chẩn đoán kỹ thuật.',
    icon: BarChart3,
  },
  {
    key: 'admin-users',
    workspace: 'admin',
    group: 'Hệ thống',
    label: 'Tài khoản & giảng viên',
    description: 'Quản lý tài khoản, giảng viên và dữ liệu import.',
    icon: Users,
  },
  {
    key: 'admin-academic',
    workspace: 'admin',
    group: 'Học vụ',
    label: 'Học kỳ & lớp học',
    description: 'Quản lý học kỳ, môn học và lớp học phần.',
    icon: Library,
  },
  {
    key: 'admin-reindex',
    workspace: 'admin',
    allowedAccountRoles: [ACCOUNT_ROLES.ADMIN],
    group: 'Giám sát AI',
    label: 'Reindex tài liệu',
    description: 'Tạo lại chỉ mục chữ và hình ảnh cho toàn bộ học liệu trong hệ thống.',
    icon: RefreshCw,
  },
  {
    key: 'admin-ai-logs',
    workspace: 'admin',
    group: 'Giám sát AI',
    label: 'Nhật ký hỏi đáp AI',
    description: 'Theo dõi câu hỏi, câu trả lời, tiến trình và token ước tính.',
    icon: FileText,
  },
  {
    key: 'admin-answer-cache',
    workspace: 'admin',
    allowedAccountRoles: [ACCOUNT_ROLES.ADMIN],
    group: 'Giám sát AI',
    label: 'Cache câu trả lời AI',
    description: 'Quản lý cache semantic: duyệt, sửa, tắt hoặc xóa câu trả lời AI đã lưu.',
    icon: Database,
  },
];

export const getNavigationForRole = (role) => {
  const accountRole = normalizeAccountRole(role);
  const workspace = getWorkspaceRole(accountRole);
  const items = navigationItems.filter((item) => (
    item.workspace === workspace
    && (!item.allowedAccountRoles || item.allowedAccountRoles.includes(accountRole))
  ));
  if (workspace === 'senior') {
    const order = { 'senior-review': 0, 'senior-answer-cache': 1, 'senior-v2': 2 };
    return items.sort((left, right) => (order[left.key] ?? 99) - (order[right.key] ?? 99));
  }
  return items;
};
